export const TAX_KNOWLEDGE_FOUNDATION = {
  version: "Tax Year 2026 · reviewed starter knowledge catalogue",
  reviewedOn: "26 August 2026",
  limitation: "This is a small, reviewed preparation catalogue, not a live legal database, a complete tax-rule database, or a determination of any person's filing position.",
  limitationUrdu: "یہ تیاری کے لیے ایک محدود، جائزہ شدہ کیٹلاگ ہے؛ لائیو قانونی ڈیٹابیس، مکمل ٹیکس رول ڈیٹابیس یا کسی فرد کی فائلنگ پوزیشن کا تعین نہیں۔",
  citationLabel: "Official source · reviewed guidance",
  citationLabelUrdu: "سرکاری ذریعہ · جائزہ شدہ رہنمائی",
  topics: [
    {
      id: "iris-access",
      title: "IRIS access and first-time filing",
      titleUrdu: "آئرس رسائی اور پہلی بار فائلنگ",
      purpose: "Use FBR's official filing guidance to check the current IRIS access and first-time registration route before starting. This site cannot open or operate your IRIS account.",
      purposeUrdu: "شروع کرنے سے پہلے آئرس رسائی اور پہلی بار رجسٹریشن کا موجودہ راستہ ایف بی آر کی سرکاری فائلنگ رہنمائی سے دیکھیں۔ یہ سائٹ آپ کا آئرس اکاؤنٹ نہیں کھول سکتی اور نہ چلا سکتی ہے۔",
      sourceLabel: "FBR: File Income Tax Return",
      sourceUrl: "https://www.fbr.gov.pk/categ/file-income-tax-return/51147/80860/71158",
      reviewedOn: "26 August 2026",
      scope: "Official IRIS access and first-time filing orientation only; verify any account-specific requirement in IRIS.",
      scopeUrdu: "صرف سرکاری آئرس رسائی اور پہلی بار فائلنگ کی ابتدائی رہنمائی؛ اکاؤنٹ سے متعلق ہر شرط آئرس میں تصدیق کریں۔",
      preparationLinks: [
        { id: "iris-walkthrough", label: "Guided IRIS orientation", labelUrdu: "آئرس رہنمائی" },
        { id: "taxpayer-path", label: "Tailored preparation checklist", labelUrdu: "ذاتی تیاری چیک لسٹ" },
      ],
    },
    {
      id: "return-completion-records",
      title: "Return completion and private record keeping",
      titleUrdu: "ریٹرن مکمل کرنا اور نجی ریکارڈ رکھنا",
      purpose: "Use FBR's official filing guidance to review the current completion, filing, record-keeping, and privacy topics before acting. Keep your own records private and follow FBR's current route.",
      purposeUrdu: "عمل سے پہلے موجودہ مکمل کرنے، فائلنگ، ریکارڈ رکھنے اور رازداری کے موضوعات ایف بی آر کی سرکاری فائلنگ رہنمائی سے دیکھیں۔ اپنے ریکارڈ نجی رکھیں اور ایف بی آر کا موجودہ راستہ استعمال کریں۔",
      sourceLabel: "FBR: File Income Tax Return",
      sourceUrl: "https://www.fbr.gov.pk/categ/file-income-tax-return/51147/80860/71158",
      reviewedOn: "26 August 2026",
      scope: "Educational record-preparation orientation only; it does not confirm which records are legally sufficient for a person.",
      scopeUrdu: "صرف تعلیمی ریکارڈ تیاری رہنمائی؛ یہ تصدیق نہیں کرتی کہ کسی فرد کے لیے کون سے ریکارڈ قانونی طور پر کافی ہیں۔",
      preparationLinks: [
        { id: "pre-submission", label: "Pre-submission error prevention", labelUrdu: "جمع کرانے سے پہلے غلطی سے بچاؤ" },
        { id: "post-submission", label: "Post-submission continuity", labelUrdu: "جمع کرانے کے بعد تسلسل" },
      ],
    },
    {
      id: "wealth-statement-reconciliation",
      title: "Wealth Statement and reconciliation preparation",
      titleUrdu: "ویلتھ اسٹیٹمنٹ اور ری کنسیلی ایشن تیاری",
      purpose: "Use FBR's official filing guidance as the starting point for reviewing the Wealth Statement route and keep the arithmetic and supporting records under your own control.",
      purposeUrdu: "ویلتھ اسٹیٹمنٹ کے راستے کا جائزہ لینے کے لیے ایف بی آر کی سرکاری فائلنگ رہنمائی سے آغاز کریں اور حساب و معاون ریکارڈ اپنے کنٹرول میں رکھیں۔",
      sourceLabel: "FBR: File Income Tax Return",
      sourceUrl: "https://www.fbr.gov.pk/categ/file-income-tax-return/51147/80860/71158",
      reviewedOn: "26 August 2026",
      scope: "Official filing-workflow starting point only; this site does not confirm a Wealth Statement, classify an asset, or determine an FBR outcome.",
      scopeUrdu: "صرف سرکاری فائلنگ ورک فلو کا ابتدائی ذریعہ؛ یہ سائٹ ویلتھ اسٹیٹمنٹ، اثاثے کی درجہ بندی یا ایف بی آر نتیجہ طے نہیں کرتی۔",
      preparationLinks: [
        { id: "reconciliation-workbench", label: "Local reconciliation workbench", labelUrdu: "مقامی ری کنسیلی ایشن ورک بینچ" },
        { id: "return-preparation", label: "Return preparation route", labelUrdu: "ریٹرن تیاری کا راستہ" },
      ],
    },
    {
      id: "bank-record-cross-check",
      title: "Bank records and balance cross-check preparation",
      titleUrdu: "بینک ریکارڈ اور بیلنس کراس چیک تیاری",
      purpose: "Use the official filing and record-preparation starting point, then compare generic statement closing balances with your own Wealth Statement records outside this site.",
      purposeUrdu: "سرکاری فائلنگ اور ریکارڈ تیاری کے ابتدائی ذریعہ سے رہنمائی لیں، پھر عمومی اسٹیٹمنٹ کلوزنگ بیلنس کو اپنی ویلتھ اسٹیٹمنٹ کے ریکارڈ سے اس سائٹ سے باہر ملائیں۔",
      sourceLabel: "FBR: File Income Tax Return",
      sourceUrl: "https://www.fbr.gov.pk/categ/file-income-tax-return/51147/80860/71158",
      reviewedOn: "26 August 2026",
      scope: "Preparation prompt only; it does not identify taxable income, treat transfers, or verify any account or statement.",
      scopeUrdu: "صرف تیاری کی یاددہانی؛ یہ قابلِ ٹیکس آمدنی، منتقلی کا ٹریٹمنٹ یا کسی اکاؤنٹ/اسٹیٹمنٹ کی تصدیق نہیں کرتی۔",
      preparationLinks: [
        { id: "reconciliation-workbench", label: "Local bank cross-check", labelUrdu: "مقامی بینک کراس چیک" },
        { id: "private-records", label: "Private record preparation", labelUrdu: "نجی ریکارڈ تیاری" },
      ],
    },
    {
      id: "capital-gains-property-records",
      title: "Capital gains and property transaction records",
      titleUrdu: "کیپٹل گین اور جائیداد لین دین کے ریکارڈ",
      purpose: "Start with the official FBR laws and filing resources when reviewing property or investment transactions; keep contracts, costs, proceeds, ownership, and supporting records privately organised.",
      purposeUrdu: "جائیداد یا سرمایہ کاری کے لین دین کا جائزہ لیتے وقت ایف بی آر کے سرکاری قوانین اور فائلنگ وسائل سے آغاز کریں؛ معاہدے، لاگت، وصولی، ملکیت اور معاون ریکارڈ نجی طور پر منظم رکھیں۔",
      sourceLabel: "FBR: Laws and official filing resources",
      sourceUrl: "https://www.fbr.gov.pk/laws",
      reviewedOn: "26 August 2026",
      scope: "Preparation record only; this site does not select a tax rate, exemption, valuation rule, gain treatment, or filing position.",
      scopeUrdu: "صرف تیاری کا ریکارڈ؛ یہ سائٹ ٹیکس ریٹ، استثنا، قدر، گین ٹریٹمنٹ یا فائلنگ مؤقف منتخب نہیں کرتی۔",
      preparationLinks: [
        { id: "capital-gains-worksheet", label: "Local capital-gains worksheet", labelUrdu: "مقامی کیپٹل گین ورک شیٹ" },
        { id: "property-records", label: "Property transaction records", labelUrdu: "جائیداد لین دین ریکارڈ" },
      ],
    },
    {
      id: "due-dates",
      title: "Published due-date categories",
      titleUrdu: "شائع شدہ ڈیڈ لائن کی اقسام",
      purpose: "Use this official page to check the currently published filing-date category; do not infer an extension or personal deadline from this tool.",
      purposeUrdu: "موجودہ شائع شدہ فائلنگ تاریخ کی قسم جانچنے کے لیے یہ سرکاری صفحہ استعمال کریں؛ اس ٹول سے توسیع یا اپنی ذاتی ڈیڈ لائن اخذ نہ کریں۔",
      sourceLabel: "FBR: Income Tax due dates",
      sourceUrl: "https://www.fbr.gov.pk/categ/income-tax-due-dates/51147/40846/81148",
      reviewedOn: "26 August 2026",
      scope: "Published date categories only; it is not a personal deadline, extension, or late-filing decision.",
      scopeUrdu: "صرف شائع شدہ تاریخ کی اقسام؛ یہ ذاتی ڈیڈ لائن، توسیع یا تاخیر سے فائلنگ کا فیصلہ نہیں۔",
      preparationLinks: [
        { id: "source-update-centre", label: "Reviewed official-source update centre", labelUrdu: "جائزہ شدہ سرکاری ذرائع اپڈیٹ سینٹر" },
        { id: "pre-filing-timeline", label: "Temporary pre-filing timeline", labelUrdu: "عارضی پری فائلنگ ٹائم لائن" },
      ],
    },
    {
      id: "laws-index",
      title: "Acts, ordinances and rules index",
      titleUrdu: "ایکٹس، آرڈیننسز اور قواعد کا انڈیکس",
      purpose: "Use this official index to locate the current primary legal material relevant to a question. Seek qualified advice for interpretation.",
      purposeUrdu: "کسی سوال سے متعلق موجودہ بنیادی قانونی مواد تلاش کرنے کے لیے یہ سرکاری انڈیکس استعمال کریں۔ تشریح کے لیے اہل مشورہ لیں۔",
      sourceLabel: "FBR: Acts / Ordinances / Rules",
      sourceUrl: "https://www.fbr.gov.pk/act-rules-ordinances/131226",
      reviewedOn: "26 August 2026",
      scope: "A starting index for current primary material, not an interpretation, a complete topic search, or personalised advice.",
      scopeUrdu: "موجودہ بنیادی مواد کے لیے ابتدائی انڈیکس، تشریح، مکمل موضوعی تلاش یا ذاتی مشورہ نہیں۔",
      preparationLinks: [
        { id: "complex-situations", label: "Complex-situation preparation navigator", labelUrdu: "پیچیدہ صورتحال تیاری نیویگیٹر" },
        { id: "official-resources", label: "Official tax and investment resources", labelUrdu: "سرکاری ٹیکس اور سرمایہ کاری وسائل" },
      ],
    },
    {
      id: "contact-support-route",
      title: "Official contact and escalation route",
      titleUrdu: "سرکاری رابطہ اور رہنمائی کا راستہ",
      purpose: "Use FBR's official contact page only to find an escalation or support route for an unclear, urgent, notice, audit, demand, court, foreign, residency, or other complex matter. This site does not operate support or inspect a case.",
      purposeUrdu: "غیر واضح، فوری، نوٹس، آڈٹ، ڈیمانڈ، عدالتی، غیر ملکی، رہائشی یا دوسرے پیچیدہ معاملے کے لیے صرف رہنمائی یا سپورٹ کا راستہ تلاش کرنے کو ایف بی آر کا سرکاری رابطہ صفحہ استعمال کریں۔ یہ سائٹ سپورٹ نہیں چلاتی اور نہ ہی کسی کیس کا جائزہ لیتی ہے۔",
      sourceLabel: "FBR: Contact us",
      sourceUrl: "https://www.fbr.gov.pk/contact-us/142252/173964",
      reviewedOn: "26 August 2026",
      scope: "Official escalation-route orientation only; it does not provide an app-operated support channel, a response, a deadline, or a case outcome.",
      scopeUrdu: "صرف سرکاری رہنمائی کے راستے کی ابتدائی معلومات؛ یہ ایپ کے زیرِ انتظام سپورٹ چینل، جواب، ڈیڈ لائن یا کیس کا نتیجہ فراہم نہیں کرتی۔",
      preparationLinks: [
        { id: "fbr-notice-preparation-guide", label: "FBR notice preparation guide", labelUrdu: "ایف بی آر نوٹس تیاری گائیڈ" },
        { id: "complex-situations", label: "Complex-situation preparation navigator", labelUrdu: "پیچیدہ صورتحال تیاری نیویگیٹر" },
      ],
    },
    {
      id: "company-industry-preparation",
      title: "Company and industry official preparation routes",
      titleUrdu: "کمپنی اور صنعت کے سرکاری تیاری راستے",
      purpose: "Use the official FBR registration and filing starting points to frame internal preparation questions for a company or industrial operation. Check the current official route before acting.",
      purposeUrdu: "کمپنی یا صنعتی آپریشن کے لیے اندرونی تیاری کے سوالات ترتیب دینے کو ایف بی آر کے سرکاری رجسٹریشن اور فائلنگ ابتدائی ذرائع استعمال کریں۔ عمل سے پہلے موجودہ سرکاری راستہ دیکھیں۔",
      sourceLabel: "FBR: Register for Income Tax",
      sourceUrl: "https://www.fbr.gov.pk/categ/register-income-tax/51147/30846/71148",
      reviewedOn: "26 August 2026",
      scope: "Official preparation-route orientation only; it does not decide company status, registration, return type, sales-tax treatment, tax, deadline, or FBR acceptance.",
      scopeUrdu: "صرف سرکاری تیاری راستے کی ابتدائی معلومات؛ یہ کمپنی اسٹیٹس، رجسٹریشن، ریٹرن کی قسم، سیلز ٹیکس ٹریٹمنٹ، ٹیکس، ڈیڈ لائن یا ایف بی آر کی قبولیت طے نہیں کرتی۔",
      preparationLinks: [
        { id: "official-resources", label: "Official tax and investment resources", labelUrdu: "سرکاری ٹیکس اور سرمایہ کاری وسائل" },
        { id: "complex-situations", label: "Complex-situation preparation navigator", labelUrdu: "پیچیدہ صورتحال تیاری نیویگیٹر" },
      ],
    },
  ],
};

export const TAX_LEARNING_PATHS = [
  {
    id: "iris-start",
    title: "I want to start with official IRIS access",
    titleUrdu: "میں سرکاری آئرس رسائی سے شروع کرنا چاہتا/چاہتی ہوں",
    topicId: "iris-access",
    preparationAction: "Use the guided IRIS orientation and the tailored preparation checklist before opening IRIS.",
    preparationActionUrdu: "آئرس کھولنے سے پہلے آئرس رہنمائی اور ذاتی تیاری چیک لسٹ استعمال کریں۔",
    boundary: "This path does not open IRIS, create an account, or decide whether you can file.",
    boundaryUrdu: "یہ راستہ آئرس نہیں کھولتا، اکاؤنٹ نہیں بناتا اور نہ ہی یہ فیصلہ کرتا ہے کہ آپ فائل کر سکتے ہیں۔",
  },
  {
    id: "return-preparation",
    title: "I want to prepare a return and private records",
    titleUrdu: "میں ریٹرن اور نجی ریکارڈ کی تیاری کرنا چاہتا/چاہتی ہوں",
    topicId: "return-completion-records",
    preparationAction: "Use the pre-submission error-prevention and post-submission continuity checklists as temporary prompts.",
    preparationActionUrdu: "عارضی یاددہانی کے طور پر جمع کرانے سے پہلے غلطی سے بچاؤ اور جمع کرانے کے بعد تسلسل چیک لسٹس استعمال کریں۔",
    boundary: "This path does not verify records, calculate tax, or confirm what FBR will accept.",
    boundaryUrdu: "یہ راستہ ریکارڈ کی تصدیق، ٹیکس کا حساب یا ایف بی آر کی قبولیت کی تصدیق نہیں کرتا۔",
  },
  {
    id: "published-date-check",
    title: "I want to check a published filing-date category",
    titleUrdu: "میں شائع شدہ فائلنگ تاریخ کی قسم دیکھنا چاہتا/چاہتی ہوں",
    topicId: "due-dates",
    preparationAction: "Use the reviewed source update centre and temporary pre-filing timeline to prepare questions for FBR.",
    preparationActionUrdu: "ایف بی آر کے لیے سوالات تیار کرنے کو جائزہ شدہ سورس اپڈیٹ سینٹر اور عارضی پری فائلنگ ٹائم لائن استعمال کریں۔",
    boundary: "This path does not calculate a personal deadline, extension, or late-filing result.",
    boundaryUrdu: "یہ راستہ ذاتی ڈیڈ لائن، توسیع یا تاخیر سے فائلنگ کا نتیجہ نہیں نکالتا۔",
  },
  {
    id: "complex-question",
    title: "I have a complex or unclear tax question",
    titleUrdu: "میرا ٹیکس کا سوال پیچیدہ یا غیر واضح ہے",
    topicId: "laws-index",
    preparationAction: "Use the complex-situation navigator to select only a broad category, then check the official source or seek qualified advice.",
    preparationActionUrdu: "صرف عمومی زمرہ منتخب کرنے کے لیے پیچیدہ صورتحال نیویگیٹر استعمال کریں، پھر سرکاری ذریعہ دیکھیں یا اہل مشورہ لیں۔",
    boundary: "This path does not interpret law, determine treatment, or replace qualified advice.",
    boundaryUrdu: "یہ راستہ قانون کی تشریح، ٹریٹمنٹ کا تعین یا اہل مشورے کا متبادل نہیں۔",
  },
  {
    id: "freelancer-preparation",
    title: "I am preparing as an individual freelancer",
    titleUrdu: "میں انفرادی فری لانسر کے طور پر تیاری کر رہا/رہی ہوں",
    topicId: "return-completion-records",
    preparationAction: "Use the separate Freelancer resources and private record-preparation prompts, then confirm the current official route before acting.",
    preparationActionUrdu: "الگ فری لانسر وسائل اور نجی ریکارڈ تیاری یاددہانیاں استعمال کریں، پھر عمل سے پہلے موجودہ سرکاری راستہ تصدیق کریں۔",
    boundary: "This path does not classify your work, determine treatment or eligibility, calculate tax, or confirm what FBR will accept.",
    boundaryUrdu: "یہ راستہ آپ کے کام کی درجہ بندی، ٹریٹمنٹ یا اہلیت کا تعین، ٹیکس کا حساب یا ایف بی آر کی قبولیت کی تصدیق نہیں کرتا۔",
  },
  {
    id: "company-industry-preparation",
    title: "I am preparing for a company or industrial operation",
    titleUrdu: "میں کمپنی یا صنعتی آپریشن کے لیے تیاری کر رہا/رہی ہوں",
    topicId: "company-industry-preparation",
    preparationAction: "Use the separate Large Business & Industry official-source section to organise internal questions before an authorised person uses the official portal.",
    preparationActionUrdu: "کسی مجاز شخص کے سرکاری پورٹل استعمال کرنے سے پہلے اندرونی سوالات ترتیب دینے کو الگ بڑے کاروبار اور صنعت کے سرکاری ذرائع والا حصہ استعمال کریں۔",
    boundary: "This path does not decide company status, registration, sales-tax status, return type, tax, deadline, or FBR outcome.",
    boundaryUrdu: "یہ راستہ کمپنی اسٹیٹس، رجسٹریشن، سیلز ٹیکس اسٹیٹس، ریٹرن کی قسم، ٹیکس، ڈیڈ لائن یا ایف بی آر نتیجہ طے نہیں کرتا۔",
  },
];

export const TAX_SOURCE_TOPIC_BRIEFS = [
  {
    id: "iris-brief",
    topicId: "iris-access",
    title: "Starting with official IRIS access",
    titleUrdu: "سرکاری آئرس رسائی سے آغاز",
    summary: "Use the FBR filing guide as a starting point for current IRIS access and first-time orientation, then confirm account-specific steps in IRIS itself.",
    summaryUrdu: "موجودہ آئرس رسائی اور پہلی بار ابتدائی رہنمائی کے لیے ایف بی آر فائلنگ گائیڈ کو نقطۂ آغاز بنائیں، پھر اکاؤنٹ سے متعلق اقدامات خود آئرس میں تصدیق کریں۔",
    boundary: "This brief is an orientation card; it does not create, access, or operate an IRIS account.",
    boundaryUrdu: "یہ بریف ابتدائی کارڈ ہے؛ یہ آئرس اکاؤنٹ بناتا، رسائی حاصل کرتا یا چلاتا نہیں۔",
  },
  {
    id: "records-brief",
    topicId: "return-completion-records",
    title: "Preparing a private record trail",
    titleUrdu: "نجی ریکارڈ کی تیاری",
    summary: "Use the official filing guidance to frame your private preparation questions and keep records outside this site.",
    summaryUrdu: "اپنے نجی تیاری کے سوالات ترتیب دینے کے لیے سرکاری فائلنگ رہنمائی استعمال کریں اور ریکارڈ اس سائٹ سے باہر رکھیں۔",
    boundary: "This brief does not inspect records or confirm that they are complete or legally sufficient.",
    boundaryUrdu: "یہ بریف ریکارڈ دیکھتا نہیں اور نہ ہی ان کے مکمل یا قانونی طور پر کافی ہونے کی تصدیق کرتا ہے۔",
  },
  {
    id: "dates-brief",
    topicId: "due-dates",
    title: "Checking published date categories",
    titleUrdu: "شائع شدہ تاریخ کی اقسام دیکھنا",
    summary: "Use FBR's current due-date page to review the published category that may be relevant to your question.",
    summaryUrdu: "اپنے سوال سے متعلق ہو سکنے والی شائع شدہ قسم دیکھنے کے لیے ایف بی آر کا موجودہ ڈیڈ لائن صفحہ استعمال کریں۔",
    boundary: "This brief cannot calculate a personal deadline, extension, or late-filing result.",
    boundaryUrdu: "یہ بریف ذاتی ڈیڈ لائن، توسیع یا تاخیر سے فائلنگ کا نتیجہ نہیں نکال سکتا۔",
  },
  {
    id: "laws-brief",
    topicId: "laws-index",
    title: "Finding primary material for a question",
    titleUrdu: "سوال کے لیے بنیادی مواد تلاش کرنا",
    summary: "Use the official laws index to locate current primary material, then seek qualified help for interpretation when needed.",
    summaryUrdu: "موجودہ بنیادی مواد تلاش کرنے کے لیے سرکاری قوانین کا انڈیکس استعمال کریں، پھر ضرورت پر تشریح کے لیے اہل مدد لیں۔",
    boundary: "This brief is not an interpretation, a complete legal-topic search, or personalised advice.",
    boundaryUrdu: "یہ بریف تشریح، مکمل قانونی موضوعی تلاش یا ذاتی مشورہ نہیں۔",
  },
  {
    id: "company-industry-brief",
    topicId: "company-industry-preparation",
    title: "Preparing company and industry source questions",
    titleUrdu: "کمپنی اور صنعت کے سورس سوالات کی تیاری",
    summary: "Start with the reviewed FBR registration source, then use the separate industry resource section to review official filing, record-keeping, and sales-tax starting points as relevant to questions—not as decisions.",
    summaryUrdu: "جائزہ شدہ ایف بی آر رجسٹریشن ذریعہ سے آغاز کریں، پھر الگ صنعت وسائل حصہ استعمال کر کے سرکاری فائلنگ، ریکارڈ رکھنے اور سیلز ٹیکس ابتدائی ذرائع سوالات سے متعلق دیکھیں—فیصلوں کے طور پر نہیں۔",
    boundary: "This brief does not decide an entity’s obligations, treatment, return, registration, deadline, calculation, or outcome.",
    boundaryUrdu: "یہ بریف کسی ادارے کی ذمہ داری، ٹریٹمنٹ، ریٹرن، رجسٹریشن، ڈیڈ لائن، حساب یا نتیجہ طے نہیں کرتا۔",
  },
];

export const TAX_PREPARATION_VISUAL_JOURNEY = [
  {
    id: "choose-topic",
    label: "Choose a broad education topic",
    labelUrdu: "عمومی تعلیمی موضوع منتخب کریں",
    explanation: "Start with a reviewed topic card rather than entering private information.",
    explanationUrdu: "نجی معلومات درج کرنے کے بجائے جائزہ شدہ موضوع کارڈ سے شروع کریں۔",
  },
  {
    id: "read-source",
    label: "Open the official source",
    labelUrdu: "سرکاری ذریعہ کھولیں",
    explanation: "Check the linked FBR page directly for its current published content.",
    explanationUrdu: "موجودہ شائع شدہ مواد کے لیے لنک شدہ ایف بی آر صفحہ براہِ راست دیکھیں۔",
  },
  {
    id: "prepare-privately",
    label: "Use a local preparation prompt",
    labelUrdu: "مقامی تیاری پرامپٹ استعمال کریں",
    explanation: "Use temporary checklists or questions without entering sensitive records here.",
    explanationUrdu: "حساس ریکارڈ یہاں درج کیے بغیر عارضی چیک لسٹ یا سوالات استعمال کریں۔",
  },
  {
    id: "check-limits",
    label: "Check the source scope and limits",
    labelUrdu: "ذریعہ کا دائرہ اور حدود دیکھیں",
    explanation: "Distinguish reviewed education from live FBR information, law interpretation, or an individual result.",
    explanationUrdu: "جائزہ شدہ تعلیم کو لائیو ایف بی آر معلومات، قانونی تشریح یا انفرادی نتیجے سے الگ رکھیں۔",
  },
  {
    id: "escalate",
    label: "Use an official or qualified escalation route",
    labelUrdu: "سرکاری یا اہل رہنمائی کا راستہ استعمال کریں",
    explanation: "For unclear, urgent, foreign, notice, audit, demand, or court matters, use FBR's official route or qualified help.",
    explanationUrdu: "غیر واضح، فوری، غیر ملکی، نوٹس، آڈٹ، ڈیمانڈ یا عدالتی معاملات کے لیے ایف بی آر کا سرکاری راستہ یا اہل مدد استعمال کریں۔",
  },
];

export const TAX_PLANNING_REFLECTIONS = [
  {
    id: "official-source-first",
    title: "I want to organise an official-source check",
    titleUrdu: "میں سرکاری ذریعہ چیک ترتیب دینا چاہتا/چاہتی ہوں",
    topicId: "iris-access",
    reflection: "What current FBR page should I read first, and what account-specific step must I verify only in IRIS?",
    reflectionUrdu: "مجھے پہلے کون سا موجودہ ایف بی آر صفحہ پڑھنا چاہیے، اور کون سا اکاؤنٹ سے متعلق قدم صرف آئرس میں تصدیق کرنا ہے؟",
    boundary: "This is a general planning question, not a filing route or eligibility decision.",
    boundaryUrdu: "یہ عمومی منصوبہ بندی کا سوال ہے، فائلنگ راستہ یا اہلیت کا فیصلہ نہیں۔",
  },
  {
    id: "private-preparation-first",
    title: "I want to organise private preparation",
    titleUrdu: "میں نجی تیاری ترتیب دینا چاہتا/چاہتی ہوں",
    topicId: "return-completion-records",
    reflection: "Which broad private record categories should I review outside this site before checking official guidance?",
    reflectionUrdu: "سرکاری رہنمائی دیکھنے سے پہلے مجھے اس سائٹ سے باہر کون سے عمومی نجی ریکارڈ زمرے دیکھنے چاہییں؟",
    boundary: "Do not enter records, figures, identifiers, or documents here; this guide does not assess completeness.",
    boundaryUrdu: "یہاں ریکارڈ، اعداد، شناخت یا دستاویزات درج نہ کریں؛ یہ گائیڈ مکمل ہونے کا جائزہ نہیں لیتا۔",
  },
  {
    id: "unclear-question",
    title: "I have an unclear planning question",
    titleUrdu: "میرا منصوبہ بندی کا سوال غیر واضح ہے",
    topicId: "laws-index",
    reflection: "Can I identify a broad question and locate primary material, then seek qualified help for interpretation?",
    reflectionUrdu: "کیا میں عمومی سوال شناخت کر کے بنیادی مواد تلاش کر سکتا/سکتی ہوں، پھر تشریح کے لیے اہل مدد لوں؟",
    boundary: "This guide does not provide personalised tax planning, legal advice, or an outcome prediction.",
    boundaryUrdu: "یہ گائیڈ ذاتی ٹیکس منصوبہ بندی، قانونی مشورہ یا نتیجے کی پیش گوئی نہیں دیتا۔",
  },
];

export function getStarterKnowledgeTopics(query = "") {
  const normalizedQuery = String(query).trim().toLocaleLowerCase();
  if (!normalizedQuery) return TAX_KNOWLEDGE_FOUNDATION.topics;

  return TAX_KNOWLEDGE_FOUNDATION.topics.filter((topic) => [
    topic.title,
    topic.titleUrdu,
    topic.purpose,
    topic.purposeUrdu,
    topic.scope,
    topic.scopeUrdu,
  ].join(" ").toLocaleLowerCase().includes(normalizedQuery));
}

export function getLearningPath(pathId) {
  return TAX_LEARNING_PATHS.find((path) => path.id === pathId) ?? TAX_LEARNING_PATHS[0];
}

export function getPlanningReflection(reflectionId) {
  return TAX_PLANNING_REFLECTIONS.find((reflection) => reflection.id === reflectionId) ?? TAX_PLANNING_REFLECTIONS[0];
}
