export const TAX_KNOWLEDGE_FOUNDATION = {
  version: "Tax Year 2026 · reviewed starter knowledge catalogue",
  reviewedOn: "26 August 2026",
  limitation: "This is a small, reviewed preparation catalogue, not a live legal database, a complete tax-rule database, or a determination of any person's filing position.",
  limitationUrdu: "یہ تیاری کے لیے ایک محدود، جائزہ شدہ کیٹلاگ ہے؛ لائیو قانونی ڈیٹابیس، مکمل ٹیکس رول ڈیٹابیس یا کسی فرد کی فائلنگ پوزیشن کا تعین نہیں۔",
  citationLabel: "Official source · reviewed guidance",
  citationLabelUrdu: "سرکاری ذریعہ · جائزہ شدہ رہنمائی",
  topics: [
    {
      id: "iris-access",
      title: "IRIS access and first-time filing",
      titleUrdu: "آئرس رسائی اور پہلی بار فائلنگ",
      purpose: "Use FBR's official filing guidance to check the current IRIS access and first-time registration route before starting. This site cannot open or operate your IRIS account.",
      purposeUrdu: "شروع کرنے سے پہلے آئرس رسائی اور پہلی بار رجسٹریشن کا موجودہ راستہ ایف بی آر کی سرکاری فائلنگ رہنمائی سے دیکھیں۔ یہ سائٹ آپ کا آئرس اکاؤنٹ نہیں کھول سکتی اور نہ چلا سکتی ہے۔",
      sourceLabel: "FBR: File Income Tax Return",
      sourceUrl: "https://www.fbr.gov.pk/categ/file-income-tax-return/51147/80860/71158",
      reviewedOn: "26 August 2026",
      scope: "Official IRIS access and first-time filing orientation only; verify any account-specific requirement in IRIS.",
      scopeUrdu: "صرف سرکاری آئرس رسائی اور پہلی بار فائلنگ کی ابتدائی رہنمائی؛ اکاؤنٹ سے متعلق ہر شرط آئرس میں تصدیق کریں۔",
      preparationLinks: [
        { id: "iris-walkthrough", label: "Guided IRIS orientation", labelUrdu: "آئرس رہنمائی" },
        { id: "taxpayer-path", label: "Tailored preparation checklist", labelUrdu: "ذاتی تیاری چیک لسٹ" },
      ],
    },
    {
      id: "return-completion-records",
      title: "Return completion and private record keeping",
      titleUrdu: "ریٹرن مکمل کرنا اور نجی ریکارڈ رکھنا",
      purpose: "Use FBR's official filing guidance to review the current completion, filing, record-keeping, and privacy topics before acting. Keep your own records private and follow FBR's current route.",
      purposeUrdu: "عمل سے پہلے موجودہ مکمل کرنے، فائلنگ، ریکارڈ رکھنے اور رازداری کے موضوعات ایف بی آر کی سرکاری فائلنگ رہنمائی سے دیکھیں۔ اپنے ریکارڈ نجی رکھیں اور ایف بی آر کا موجودہ راستہ استعمال کریں۔",
      sourceLabel: "FBR: File Income Tax Return",
      sourceUrl: "https://www.fbr.gov.pk/categ/file-income-tax-return/51147/80860/71158",
      reviewedOn: "26 August 2026",
      scope: "Educational record-preparation orientation only; it does not confirm which records are legally sufficient for a person.",
      scopeUrdu: "صرف تعلیمی ریکارڈ تیاری رہنمائی؛ یہ تصدیق نہیں کرتی کہ کسی فرد کے لیے کون سے ریکارڈ قانونی طور پر کافی ہیں۔",
      preparationLinks: [
        { id: "pre-submission", label: "Pre-submission error prevention", labelUrdu: "جمع کرانے سے پہلے غلطی سے بچاؤ" },
        { id: "post-submission", label: "Post-submission continuity", labelUrdu: "جمع کرانے کے بعد تسلسل" },
      ],
    },
    {
      id: "due-dates",
      title: "Published due-date categories",
      titleUrdu: "شائع شدہ ڈیڈ لائن کی اقسام",
      purpose: "Use this official page to check the currently published filing-date category; do not infer an extension or personal deadline from this tool.",
      purposeUrdu: "موجودہ شائع شدہ فائلنگ تاریخ کی قسم جانچنے کے لیے یہ سرکاری صفحہ استعمال کریں؛ اس ٹول سے توسیع یا اپنی ذاتی ڈیڈ لائن اخذ نہ کریں۔",
      sourceLabel: "FBR: Income Tax due dates",
      sourceUrl: "https://www.fbr.gov.pk/categ/income-tax-due-dates/51147/40846/81148",
      reviewedOn: "26 August 2026",
      scope: "Published date categories only; it is not a personal deadline, extension, or late-filing decision.",
      scopeUrdu: "صرف شائع شدہ تاریخ کی اقسام؛ یہ ذاتی ڈیڈ لائن، توسیع یا تاخیر سے فائلنگ کا فیصلہ نہیں۔",
      preparationLinks: [
        { id: "source-update-centre", label: "Reviewed official-source update centre", labelUrdu: "جائزہ شدہ سرکاری ذرائع اپڈیٹ سینٹر" },
        { id: "pre-filing-timeline", label: "Temporary pre-filing timeline", labelUrdu: "عارضی پری فائلنگ ٹائم لائن" },
      ],
    },
    {
      id: "laws-index",
      title: "Acts, ordinances and rules index",
      titleUrdu: "ایکٹس، آرڈیننسز اور قواعد کا انڈیکس",
      purpose: "Use this official index to locate the current primary legal material relevant to a question. Seek qualified advice for interpretation.",
      purposeUrdu: "کسی سوال سے متعلق موجودہ بنیادی قانونی مواد تلاش کرنے کے لیے یہ سرکاری انڈیکس استعمال کریں۔ تشریح کے لیے اہل مشورہ لیں۔",
      sourceLabel: "FBR: Acts / Ordinances / Rules",
      sourceUrl: "https://www.fbr.gov.pk/act-rules-ordinances/131226",
      reviewedOn: "26 August 2026",
      scope: "A starting index for current primary material, not an interpretation, a complete topic search, or personalised advice.",
      scopeUrdu: "موجودہ بنیادی مواد کے لیے ابتدائی انڈیکس، تشریح، مکمل موضوعی تلاش یا ذاتی مشورہ نہیں۔",
      preparationLinks: [
        { id: "complex-situations", label: "Complex-situation preparation navigator", labelUrdu: "پیچیدہ صورتحال تیاری نیویگیٹر" },
        { id: "official-resources", label: "Official tax and investment resources", labelUrdu: "سرکاری ٹیکس اور سرمایہ کاری وسائل" },
      ],
    },
  ],
};
